name: Lint & Tests

on: 
  push:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with: 
          version: latest
          only-new-issues: false

  unit-tests:
    name: Unit Tests
    needs: golangci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: 1.18
      
      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v ./... -coverprofile cover.out
          
      - name: Coverage
        run: go tool cover -func cover.out
