name: Lint & Tests

on: 
  push:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read
  pull-requests: read

golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: golangci/golangci-lint-action@v2
        with: 
          version: latest
          only-new-issues: false
